### ISSUE TITLE
Quick lab title tipo 

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-ai-studio#12]
# Module: 00
#### Step: 00

Description of issue>

Title includes "Copliots" > "Copilots" https://github.com/MicrosoftLearning/mslearn-ai-studio/blob/96463a63a7baf9a5a632e2b535c3ee0fe6345027/Instructions/03-Use-prompt-flow-chat.md?plain=1#L6 

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
Thanks - fixed
