### ISSUE TITLE
AI-3016 Lab 04 "Use-own-data" - demployement time in AI Studio

### ISSUE THREAD

**Issue by azakharovams** [MicrosoftLearning/mslearn-ai-studio#14]
# Module: 05 Apply grounding to your copilot by adding data in the Azure AI Studio
#### Step: 2

Description of issue

I'd like to inform you about an issue related to importing your own data into AI Studio. There seems to be a delay between creating an index and the model recognizing this index. I did some tests and experienced this firsthand when I deployed a new index yesterday and encountered an error for about an hour post-deployment, stating: “‘indexName’ is a required parameter for the AzureCognitiveSearch data source type.” It worked well the day after the deployment. It appears there’s a significant delay in the recognition of newly created indexes, so please consider this in your future deliveries. Maybe you could include a warning on the instructions or find an alternative solution. Thank you.

**Comment by ivorb** [comment]
Is this still causing issue? Often times these are transient issues with the product, and resolve themselves. If you're still seeing this happen, we can add a warning or something similar.

**Comment by azakharovams** [comment]
This issue is still occurring. It would be helpful to add a warning or some other indication to alert users of this potential problem.









[cid:7cb36ed7-c824-4419-9596-c162d1fb8a49]

Alexandra Zakharova
Microsoft Technical Trainer
***@***.******@***.***>

Learn.Microsoft.com<https://learn.microsoft.com/>

#SparkPossibility

[cid:1bf4523d-9f90-4515-a9d7-be6093d673cf][cid:5c808dbf-a9cb-4b35-8d1d-9d6adb7aa8a0][cid:038ded62-87f1-464f-94e8-eb55c18c400f]­­[cid:2ffe2441-1953-40de-b2a5-f86dd9470925][cid:f6abd790-7c12-4537-ac57-3e072c94b496][cid:9351d675-408b-44e2-bbb8-61d030a4ce91][cid:e2f2725e-c9f1-4aa2-9063-b1b810ecd74d][cid:6ebd9347-0e0f-4486-b120-f3e26b16af1b][cid:16dfbd3d-02a4-4983-829a-5e89953a05f6][cid:3720c759-e897-4979-8de2-49c8d0ccc93b][cid:7995a482-b3c9-416c-acd9-751721b94c52]­­­­­­[cid:b3202ebc-3dbc-427a-9273-85ef5e2c069c][cid:708ec581-c4fb-4667-a5a1-f27767ff7e63][cid:74e71a99-3d4c-4c65-9484-e4f065dd8bea][cid:7b5c23d4-21f1-4a91-8b47-d5a7915a53f2]­­



    ­­





________________________________

**Comment by ivorb** [comment]
Added a not about possible wait times for index to appear

**Comment by azakharovams** [comment]
[like]  Alexandra Zakharova reacted to your message:
________________________________
