### ISSUE TITLE
Evaluate option  in Azure AI Studio

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-ai-studio#15]
https://github.com/MicrosoftLearning/mslearn-ai-studio/blob/5894d5dc1bb2b4f90823f0d16a60dee640c26a08/Instructions/07-Evaluate-prompt-flow.md?plain=1#L89

Evaluate option may have changed in the studio. The UI offers two options (does not open an new window). And the new window does not keep the system message for me.
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/e7d4d512-af45-4d8b-9a15-b84be2513d5e">
<img width="1243" alt="image" src="https://github.com/user-attachments/assets/33a596f8-3d84-4f11-aa62-da577923a0a2">

**Comment by Skillable-MelieKrichko** [comment]
In a QA this week, we saw the same issue.

**Comment by ivorb** [comment]
We'll investigate, and update as necessary. Thanks for the heads up!

**Comment by azakharovams** [comment]
@ivorb thank you, any updates on it?

**Comment by ivorb** [comment]
fixed with [7ad8bed](https://github.com/MicrosoftLearning/mslearn-ai-studio/commit/7ad8bed3259405a045884ff01ec91eee762223d9)
