### ISSUE TITLE
Potentially outdated instructions in "Explore content filters..." exercise

### ISSUE THREAD

**Issue by CoolSpot** [MicrosoftLearning/mslearn-ai-studio#16]
# Module: Responsible generative AI
#### Step: 1 - In the Build page, select Content filters in the left navigation bar

Description of issue
Instructions refer to non-existent UI element.

Repro steps:

1. Open https://microsoftlearning.github.io/mslearn-ai-studio/Instructions/06-Explore-content-filters.html
2. Follow steps till section "Explore content filters"
3. The section tells student to "In the Build page, select Content filters in the left navigation bar, then select + Create content filter."
4. As far as I can tell, such UI does not exist there and was moved into Components (left menu section) -> Content filters

No "Build" page/section/button here:
![image](https://github.com/user-attachments/assets/58d43fac-64e8-4f49-b764-dc09021ac220)

After model deployment, user ends up on this page, where they should click "Content filters" and then "+ Create content filter" (there is no "Build" page or other UI:
![image](https://github.com/user-attachments/assets/b12a8fd0-61d4-4fa5-b504-daba039df1c2)

**Comment by afelix-95** [comment]
Thanks for pointing out the UI changes! The instructions are now updated.
