### ISSUE TITLE
Lab 1 - Creating an Azure AI hub

### ISSUE THREAD

**Issue by msftnutta** [MicrosoftLearning/mslearn-ai-studio#26]
# Module: 1
#### Step: 1

Description of issue

For Create an Azure AI hub section, step 1

Repro steps:

1. Location: Select Help me choose and then select gpt-35-turbo in the Location helper window and use the recommended region*

There is nothing shows here, unable to see the list of the models, please see screen shot below for reference. 

![image](https://github.com/user-attachments/assets/0c1a1040-ec8c-4973-b9a5-6d1d56076f63)

Understand that this could be due to UI issue but i think we should provide some additional info for example, choose Australia East, etc ... if the list of models doesn't get fully loaded.

**Comment by ivorb** [comment]
This does load for me, and given all the other issues we're seeing in AI Studio at the moment I believe it's a product bug folks will likely intermittently see. I'll reopen the issue if this persists.
