### ISSUE TITLE
Lab 4 - Build copilots with Azure AI Studio

### ISSUE THREAD

**Issue by msftnutta** [MicrosoftLearning/mslearn-ai-studio#28]
#### Step: Evaluate your copilot with the built-in metrics

Description of issue

Step 1, there is no option from the UI for What kind of scenario are you evaluating?: Question and answer without context, please see the screen shot below

![image](https://github.com/user-attachments/assets/f9139838-5da1-49a1-a8fc-dd1b38bf013e)

But I do see something at the bottom,

![image](https://github.com/user-attachments/assets/b8b54b27-e53d-45b0-a43b-74458417a855)

Probably the UI changed ?

**Comment by ivorb** [comment]
Looks like a UI change, I'll update the instructions

**Comment by madiepev** [comment]
Instructions have been updated in latest PR. Thanks for reporting!
