### ISSUE TITLE
LAB 5 - Deploy the fine-tuned model

### ISSUE THREAD

**Issue by HashirSajjad** [MicrosoftLearning/mslearn-ai-studio#37]
# Module: 5
#### Step: 02

Description of issue:
Deployment of Finetune model fails every time it is being deployed. 
FYI, I have used the suggested location for gpt-35-turbo but still same results.

The error says: 
Validation error: The workspace MSI does not have deployment/write permissions to the underlying resource.

![image](https://github.com/user-attachments/assets/64c3c809-eec0-4874-9fca-b5be2e5cc7a5)

**Comment by madiepev** [comment]
This can be related to security policies in your subscription. Try out the troubleshoot tips mentioned in the instructions:
- In the Azure portal, select the AI Services resource.
- On the IAM page, in the Identity tab, confirm that it is system assigned managed identity.
- Navigate to the associated Storage Account. On the IAM page, add role assignment Storage blob data reader.
- Under Assign access to, choose Managed Identity, + Select members, and select the All system-assigned managed identities.
- Review and assign to save the new settings and retry the previous step.

**Comment by Nimra-Maryam** [comment]
Still encountering the same error despite following the instructions above.

![Image](https://github.com/user-attachments/assets/eac4dc93-84af-4119-a804-396cb56e9ec0)
