### ISSUE TITLE
Give role to AI hub and Project

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-ai-studio#38]
https://github.com/MicrosoftLearning/mslearn-ai-studio/blob/01705f2463219a9ad66ef0be2133efc290c82cd3/Instructions/04-Use-own-data.md?plain=1#L140

The issue was fixed with my learners giving the mentioned role to the AI hub and AI project, not the AI service

**Comment by ivorb** [comment]
@unaihuete93 the blob storage reader to the hub and project? Are you still hitting this? Running through the creation for fine-tuning no longer hits this issue, but let me know if you're still seeing it

**Comment by unaihuete93** [comment]
Sorry @ivorb I had no AI-3016 deliveries the last 2 weeks. I will try again.

**Comment by unaihuete93** [comment]
Just tried the lab from the skillable vm, had no issues (no need for troubleshooting part). The SA has the following RBACs by default 
![image](https://github.com/user-attachments/assets/2357d1eb-b5ca-43bf-acba-956e16d1b7aa)
Looks like the reader role is not neccesary anymore
