### ISSUE TITLE
Lab 03: Can't create AI Hub

### ISSUE THREAD

**Issue by afelix-95** [MicrosoftLearning/mslearn-ai-studio#5]
# Module: 00
#### Step: 02

Description of issue

Test done in Skillable environment.
Every time I try to create a project, a BadRequest error shows up and it fails to create the AI Hub. I created Azure AI Search resources in all the locations mentioned in the instructions and tried to create the hub in their matching options but the error is the same for all of them.

Repro steps:

![Screenshot 2024-05-09 145157](https://github.com/MicrosoftLearning/mslearn-ai-studio/assets/148110824/d51b9d4a-03d5-4847-b984-415ca7d9edb5)

**Comment by ivorb** [comment]
@afelix-95 have you been able to in the past? I could create a hub 2 hours ago, so wondering if it's a transient issue or possibly permissions?

**Comment by ivorb** [comment]
@afelix-95 following up with skillable on missing permissions

**Comment by ivorb** [comment]
this has been resolved
