### ISSUE TITLE
Lab 03: Wizard window clipping

### ISSUE THREAD

**Issue by afelix-95** [MicrosoftLearning/mslearn-ai-studio#6]
# Module: 00
#### Step: 02

Description of issue

When selecting a deployment model, if the **Show description** option is enabled, the **Confirm** button doesn't appear in the Wizard window. It is necessary to disable that option and even so the edges of the window are visibly clipped (the scrolling bar moves only the main content in the window, it doesn't affect the button's visibility). Probably an issue of compatibility/adaptability of the UI to the low screen resolution in the VM.

Wizard window with **Show description** enabled:
![Screenshot 2024-05-16 152350](https://github.com/MicrosoftLearning/mslearn-ai-studio/assets/148110824/5515340e-f4d3-4840-9543-edf2c5b406d1)

Wizard window with **Show description** disabled:
![Screenshot 2024-05-16 153909](https://github.com/MicrosoftLearning/mslearn-ai-studio/assets/148110824/b2f7426c-b7ea-4077-b157-9df6f51d561d)

**Comment by ivorb** [comment]
Been discussed with Skillable, and tracking there
