### ISSUE TITLE
Some screen shots and navigation instructions are outdated

### ISSUE THREAD

**Issue by ebwinters** [MicrosoftLearning/mslearn-ai-studio#9]
# Module: 5/7
#### Step: 5

Description of issue
Some screen shots and navigation instructions are out of date. For example, the learning module 
![image](https://github.com/MicrosoftLearning/mslearn-ai-studio/assets/4297028/c865dfe8-e48f-46bd-b5d0-43df7b890e36)

but really there is no playground page under tools, it has been moved out to its own subtab like below
![image](https://github.com/MicrosoftLearning/mslearn-ai-studio/assets/4297028/06752d93-e632-497a-8ffb-cc5710bc6bd5)

**Comment by madiepev** [comment]
Thanks for reporting the issue. Screenshots and instructions have been updated.
